name: Build and Deploy Gatsby Site

# Run the workflow when a Contentful webhook is triggered
on:
  repository_dispatch:
    types: [contentful.deploy]
  push:
    branches: final

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        run: yarn build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: public_html/
          protocol: ftps
