name: Build and Deploy Gatsby Site

# Run the workflow when a Contentful webhook is triggered
on:
  push:
    branches: final
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        run: yarn build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './public/'
          server-dir: 'public_html/'
          protocol: 'ftps'
